### ISSUE TITLE
Late-bind variable interpolation via YAML tag

### ISSUE THREAD

**Issue by jgraichen** [jgraichen/salt-tower#2]
Late-bind variable interpolation should be marked in the YAML file and finally handled by the tower e.g.:

```yaml
# jinja | yamlet

data:
  var: 5
  result: !format "some late bound key with {data.val}"
```

This is much safer than late bound formatting the whole pillar but requires extensive interaction between the yamlet renderer and the salt tower.
