### ISSUE TITLE
Configure salt environments directly in ext_pillar configuration

### ISSUE THREAD

**Issue by jgraichen** [jgraichen/salt-tower#4]
The tower pillar should be configurable to load a specific top file based on the salt environment, e.g.:
```
ext_pillar:
- tower: 
    salt:env:
      base: /srv/salt/pillar/tower.sls
      staging: /src/salt/pillar-staging/tower.sls
```

This way one can have different pillars directories/checkouts for different environments and easily test changes on actual minions by passing the e.g. staging environment to a highstate.
