### ISSUE TITLE
how to debug errors

### ISSUE THREAD

**Issue by vtolstov** [jgraichen/salt-tower#9]
how to deal with errors like:
```
Error encountered while rendering pillar top file
```

i known that i somewhere have error, but how to find it?

**Comment by vtolstov** [comment]
top.sls
```
base:
  - '*':
      - nodes/z1_unistack_org/mn01.sls
#      - nodes/z1_unistack_org/mn01/*.sls
```

```
[DEBUG   ] Rendered data from file: /srv/salt/pillars/nodes/z1_unistack_org/mn01.sls:
nodes:
  mn01.z1.unistack.org:
    roles: [ common ]
```

**Comment by vtolstov** [comment]
why it fails?

**Comment by jgraichen** [comment]
Great you found a solution! I assume you tried using the `top.sls` instead of e.g. `tower.sls` file in the default pillar directory?

This would salts own pillar rendering...

**Comment by vtolstov** [comment]
Yes, I'm use top.sls
Does it possible to disable salt top.sls rendering?

**Comment by jgraichen** [comment]
Not sure, but I do think that this cannot be disabled.

I do have a practically empty `top.sls`, and everything else in the `tower.sls`.

**Comment by vtolstov** [comment]
does it possible to detect inside top.sls who runs it salt-tower or plain salt ?

**Comment by jgraichen** [comment]
I do recommend to use `top.sls` for salt only, and `tower.sls` for tower.

I usually have a pillar directory for example like this:

````
pillar
|- common/
|- files/
|- minion/
|- roles/
|- top.sls
\- tower.sls
```

The `top.sls` is very minimal, usually only to bootstrap a minimal salt master from a masterless minion, e.g.:

```
# top.sls
base:
  'salt-master':
    - roles/salt/master
```

```
# roles/salt/master.sls
states:
  - salt/minion
  - salt/master

salt:
  minion:
    master: localhost
  master:
    fileserver_backend: [rootfs, gitfs]
    ext_pillar:
      - tower: /srv/salt/pillar/tower.sls
    file_roots:
      base: [/srv/salt/states]
```

This minimal pillar, together with the states, configures the salt master and installs the salt tower extension as I need it.

With the second run the minion starts using the master, that now uses salt-tower and the `tower.sls`:

```
# tower.sls
base:
  - common/*.sls
  - minion/{{ minion_id }}/*.sls
  # ...
```

This installs and configured everything else and all other minions. Salts own pillar is not used for anything beside the master itself.

It might be possible to have an empty `top.sls` like `base: {}` but I have not tried it here right now.
